spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      location: /upload
      max-file-size: 1MB
      max-request-size: 10MB

org:
  yunhwan:
    upload:
      path: /upload